models/data.py
from boot import db, ma


class Data(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    field = db.Column(db.String(100))

class DataSchema(ma.ModelSchema):
    class Meta:
        model = Data


data_schema_many = DataSchema(many=True)
data_schema = DataSchema()

views/__init__.py
import numpy as np
import pandas as pd
from flask import Blueprint, render_template, request

base = Blueprint('base', __name__)
books = pd.read_csv('./books.csv').fillna(1)


@base.route('/')
def index():
    books = pd.read_csv('~/workspaces/Collage/spk/dataset/books.csv').fillna(1)
    return render_template('index.html', books=books[:100])


@base.route('/calculate', methods=['post'])
def calculate():
    books = pd.read_csv('./books.csv').fillna(1)[:100]
    isMaxRate = request.form.get('max-rate', 'off') == "on"
    isMaxYear = request.form.get('max-year', 'off') == "on"
    yearWeight = request.form['year-weight']
    rateWeight = request.form['rate-weight']

    bookRates = np.array(books[['average_rating']])
    bookYears = np.array(books[['original_publication_year']])

    weights = np.array([[int(rateWeight), int(yearWeight)]]) / 100

    rateNorm = bookRates / bookRates.max() if isMaxRate else bookRates.min() / bookRates
    yearNorm = bookYears / bookYears.max() if isMaxYear else bookYears.min() / bookYears
    normalized = np.concatenate((rateNorm, yearNorm), axis=1)

    V = np.matmul(normalized, weights.transpose())
    books['V'] = V
    books = books.sort_values(by=['V'], ascending=False)
    return render_template('result.html', books=books[:3], yearWeight=yearWeight, rateWeight=rateWeight,
                           isMaxRate=('minimalkan', 'maksimalkan')[isMaxRate], isMaxYear=('minimalkan', 'maksimalkan')[isMaxYear])

templates/index.html
{% extends 'layout.html' %}
{% block content %}
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Table buku {{ hasil or '' }}</h3>
                <p class="text-muted">Dibawah adalah daftar 100 buku dari 10000 buku yang ada</p>
            </div>
            <table class="table table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Avg Rating</th>
                    <th>Year</th>
                </tr>
                </thead>
                <tbody>
                {% for _, book in books.iterrows() %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ book['title'] }}</td>
                        <td><i class="text-warning fa fa-star"></i> {{ book['average_rating'] }}</td>
                        <td>{{ book['original_publication_year'] }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rekomendasi Buku</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}">
    <style>
        body {
            padding-top: 100px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <a class="navbar-brand" href="/">Rekomendasi Buku - SAW</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

</nav>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{{ url_for('base.calculate') }}">
                        <h4 class="card-title">
                            Bobot Rating
                        </h4>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Bobot (%)</label>
                            <input type="number" class="form-control"
                                   placeholder="Contoh: 50" name="rate-weight">
                        </div>
                        <div class="form-check">
                            <input type="checkbox" name="max-rate" class="form-check-input">
                            <label class="form-check-label">Centang jika ingin rekomendasi rating
                                tertinggi</label>
                        </div>
                        <hr>
                        <h4 class="card-title">
                            Bobot Tahun
                        </h4>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Bobot (%)</label>
                            <input type="number" class="form-control"
                                   placeholder="Contoh: 50" name="year-weight">
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" name="max-year">
                            <label class="form-check-label">Centang jika ingin rekomendasi tahun
                                terakhir</label>
                        </div>
                        <br>
                        <button type="submit" class="btn btn-outline-secondary">Cek rekomendasi</button>
                    </form>
                </div>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/result.html
{% extends 'layout.html' %}
{% block content %}
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Hasil perhitungan SAW</h3>
                <p class="text-muted">Hasil dibawah terurut berdasarkan nilai V tertinggi berdasarkan bobot <span
                        class="text-info">Rating = {{ rateWeight }}%</span> dan bobot <span
                        class="text-info">Tahun = {{ yearWeight }}%</span>. Dimana parameter <b class="text-info">Rating
                    akan di{{ isMaxRate }}</b> dan parameter <b class="text-info">Tahun akan di{{ isMaxYear }}</b></p>
            </div>
            <table class="table table-hover">
                <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>V</th>
                    <th>Title</th>
                    <th>Avg Rating</th>
                    <th>Year</th>
                </tr>
                </thead>
                <tbody>
                {% for _, book in books.iterrows() %}
                    <tr>
                        <td>
                            {% if loop.index == 1 %}
                                <h3>{{ loop.index }}</h3>
                            {% elif loop.index == 2 %}
                                <h4>{{ loop.index }}</h4>
                            {% elif loop.index == 3 %}
                                <h5>{{ loop.index }}</h5>
                            {% else %}
                                {{ loop.index }}
                            {% endif %}</td>
                        <td>{{ book['V']|round(3) }}</td>
                        <td>{{ book['title'] }}</td>
                        <td><i class="text-warning fa fa-star"></i> {{ book['average_rating'] }}</td>
                        <td>{{ book['original_publication_year'] }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}